let week = prompt("1-7 сандарын енгізіңіз:");
switch (week) {
  case '1': 
    case 1:
        alert("Дүйсенбі");
        break;
  case "2":      
    case 2:
        alert("Сейсенбі");
        break;
  case "3":      
    case 3:
        alert("Сәрсенбі");
        break; 
  case "4":       
    case 4:
        alert("Бейсенбі");
        break; 
  case "5":       
    case 5:
        alert("Жұма");
        break;
  case "6":     
    case 6:
        alert("Сенбі");
        break;
  case "7":  
    case 7:
        alert("Жексенбі");
        break;    
    default:
        alert("1-7 сандарын енгізіңіз!");              
}
